name: swiftify_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  file_database:
    path: packages/file_database
  swiftify_data_repository:
    path: packages/swiftify_data_repository
  swiftify_data_source:
    path: packages/swiftify_data_source

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^7.0.0
