name: swiftify_data_repository
description: A package to request data to firestore.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  api_client:
    path: ../api_client
  file_database:
    path: ../file_database
  swiftify_data_source:
    path: ../swiftify_data_source

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
